service:
  name: BMICalculator

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/BMITable

resources:
  Resources:
    BMITable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BMITable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          
        KeySchema:
          - AttributeName: id
            KeyType: HASH
  
functions:
  bmicalculatorservice:
    handler: src/handlers/bmicalculator.handler
    events:
      - http:
          method: GET
          path: /bmicalculator
  bmicreateservice:
    handler: src/handlers/bmicreate.handler
    events:
      - http:
          method: POST
          path: /bmi
  bmigetservice:
    handler: src/handlers/bmiget.handler
    events:
      - http:
          method: GET
          path: /bmi
